services:
  - type: web
    name: medguardx-backend
    env: python
    region: oregon
    plan: free
    repo: https://github.com/adarshcod30/MedGuardX.git
    branch: main
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python -m spacy download en_core_web_lg"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MEDGUARDX_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: "https://your-vercel-domain.vercel.app" # Update this to your Vercel URL once deployed
